// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rmlbxryqbwvhqmwvsrix.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJtbGJ4cnlxYnd2aHFtd3Zzcml4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNTc3MzQsImV4cCI6MjA2ODgzMzczNH0.AX9zyVhnvibtiE8yEIeL3_Jr0-cOEa5JMNrJtz2qTlc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});